spring.application.name=springbootessentialsJPA

# Dados de conexão com o banco H2
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.username=sa
spring.datasource.password=
# H2 Client
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
# JPA, SQL
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# JWT
application.security.jwt.expiration=${JWT_EXPIRATION:900000}
application.security.jwt.secret-key=${JWT_KEY: Vx1B1MnPjfEjDTD4mD-5fBt=TbPB1xQZAGtH439E2ml0wN4mNr1z3P_AhtCzhqeNJjc=_SDj$VQFncU7bHwBB6KjrwTsk6S#cxTBrLuO!XUNUdBlbhMxAmYzV!dEzBzD-HP64EEFNfRGe3T5ffOVPFy_91V3C$X12Pd-RVh_w6ee793cB_5HWdE9WdQ-IyU8AFA7DJCiG-d9XuYZM10&Q4Ji0#4tmGuucDQmPVcMJaxVuOC1IvzfTkEdv!TP=OeB2w4p2DL$Z8MegeNEkTH=eIz&84=LGAbvUmlx$4Uxq1zCxXSXkOOO2dk$ZJLcS1AbA9f2g3GxPGTEHi8koG#EG5PI
}